# Generated by Django 4.1 on 2023-08-16 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asprak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=15)),
                ('dosen', models.CharField(max_length=50)),
                ('kontak', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=4)),
                ('lantai', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('SN', 'Senin'), ('SL', 'Selsasa'), ('RB', 'Rabu'), ('KM', 'Kamis'), ('JM', 'Jumat'), ('SB', 'Sabtu')], default='SN', max_length=2)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('kode', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Praktikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=3)),
                ('kelas', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlotPraktikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asprak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadwal_praktikum.asprak')),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadwal_praktikum.jadwal')),
                ('praktikan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadwal_praktikum.praktikan')),
            ],
        ),
        migrations.CreateModel(
            name='PlotMatkul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asprak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadwal_praktikum.asprak')),
                ('matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadwal_praktikum.matkul')),
            ],
        ),
        migrations.AddField(
            model_name='jadwal',
            name='matkul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jadwal_praktikum.matkul'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='ruang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jadwal_praktikum.ruang'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='sesi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jadwal_praktikum.sesi'),
        ),
    ]
