# Generated by Django 4.1 on 2023-08-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal_praktikum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asprak',
            options={'verbose_name_plural': 'Asprak'},
        ),
        migrations.AlterModelOptions(
            name='jadwal',
            options={'verbose_name_plural': 'Jadwal'},
        ),
        migrations.AlterModelOptions(
            name='matkul',
            options={'verbose_name_plural': 'Matkul'},
        ),
        migrations.AlterModelOptions(
            name='plotmatkul',
            options={'verbose_name_plural': 'Plot Matkul'},
        ),
        migrations.AlterModelOptions(
            name='plotpraktikan',
            options={'verbose_name_plural': 'Plot Praktikan'},
        ),
        migrations.AlterModelOptions(
            name='praktikan',
            options={'verbose_name_plural': 'Praktikan'},
        ),
        migrations.AlterModelOptions(
            name='ruang',
            options={'verbose_name_plural': 'Ruang'},
        ),
        migrations.AlterModelOptions(
            name='sesi',
            options={'verbose_name_plural': 'Sesi'},
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='kelas',
        ),
        migrations.AddField(
            model_name='asprak',
            name='kelas',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
