# Generated by Django 4.1 on 2023-08-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal_praktikum', '0002_alter_asprak_options_alter_jadwal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asprak',
            name='kelas',
        ),
        migrations.AddField(
            model_name='jadwal',
            name='kelas',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
